version: "3"

services:
  node-block-1:
    build: ./
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    environment:
      ENV_DB_HOST: 'mysql'
      ENV_DB_NAME: 'blockchain'
      ENV_DB_USER: 'root'
      ENV_DB_PASSWORD: 'Root@123'
    links:
      - mysql-1

  mysql-1:
    
    image: "mysql"
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    volumes:
    - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Root@123"
      MYSQL_DATABASE: "blockchain"

